language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  committer-from-gh: true
  on:
    branch: master